### ISSUE TITLE
Incorrect Units on CAN Protocol 4.1 Stubs 

### ISSUE THREAD

**Issue by EnDeRWiGiN** [gbmhunter/blog#23]
For the line that says 

> - "Bueno Electric’s Maximum Cable Length For a CAN Bus page gives a maximum cable stub length of 0.3mm for all speeds from 50kb/s to 1Mb/s." 

The Maximum cable stub length should change to 0.3 meters

PS: Love the site I will be using it often in the future. I am also interested in possibly making my own

**Comment by gbmhunter** [comment]
@EnDeRWiGiN for some reason I didn't get an email notification about this issue, just saw it now. Fixed, and thanks for the info!
