### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Socolin** [gbmhunter/blog#24]
Hello,

I was reading your article https://blog.mbedded.ninja/mathematics/geometry/projective-transformations/ and at this line https://github.com/gbmhunter/blog/blob/master/content/mathematics/geometry/projective-transformations/index.md?plain=1#L134 there  is a reference to some code example https://github.com/gbmhunter/BlogAssets/tree/master/Mathematics/QuadToQuad but the link is broken.

I'm trying to implement this and I'm having some weird result for other matrice than the one in the example, if you still have the code available I would like to compare to find what's wrong with my implementation.
Edit: I finally found out the problem :)

**Comment by gbmhunter** [comment]
Hi @Socolin , sorry for some reason I didn't get an email notification when this issue was created....just seeing this now. And thanks for the info, yes woops that BlogAssets repo is private (it's meant to be public). I've fixed it, link should be working now!
